server:
  # 端口
  port: 2021
  servlet:
    # 项目名称
    context-path: /jdemo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j_test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

  jackson:
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

application:
  openstack:
    keystoneUrl: "http://10.31.1.205:5000/v3"
    consoleUrl: "10.31.1.205:6080"
    adminProjectId: "8f505eddec5842c7aab8fe7314303126"
    adminUserId: 1
    memberRole: "member"

file:
  image:
    windowPath: f:\test\upload
